import {countWords,formatTime,wordSegments,acousticActivity} from './analysis.mjs';
const $=id=>document.getElementById(id);
let state='idle',recorder,stream,recognition,clock,audioContext,blob,url,worker,job=0,workerTimeout;
let started=0,session=0,finalText='',interimText='',completedRecognition='',liveSupported=true;
let currentBins=[],currentMean=0;
const setStatus=text=>$('statusText').textContent=text;
function setState(next){state=next;$('recordBtn').disabled=['starting','recording','stopping','processing'].includes(next);$('stopBtn').disabled=next!=='recording';$('fileInput').disabled=['starting','recording','stopping','processing'].includes(next);$('retryBtn').disabled=!blob||['starting','recording','stopping','processing'].includes(next);}
function resetResults(){for(const id of ['totalDuration','wordCount','wpm','speechDuration','silenceDuration','pauseCount'])$(id).textContent='—';$('finalTranscript').textContent='Pendiente del reprocesamiento del audio.';$('segmentRows').replaceChildren();$('pauses').textContent='—';$('chartNotice').textContent='Resultado final por intervalos de 30 segundos, a partir de marcas por palabra.';currentBins=[];currentMean=0;drawChart();}
function attachAudio(value){blob=value;if(url)URL.revokeObjectURL(url);url=URL.createObjectURL(blob);$('playback').src=url;$('downloadAudio').href=url;$('downloadAudio').download=`fluidez-${Date.now()}.${blob.type.includes('mp4')?'m4a':blob.type.includes('wav')?'wav':blob.type.includes('mpeg')?'mp3':'webm'}`;$('downloadAudio').hidden=false;}
function releaseMic(){if(stream)stream.getTracks().forEach(track=>track.stop());stream=null;}
function tick(){const elapsed=(performance.now()-started)/1000;$('timer').textContent=formatTime(elapsed);const words=countWords(`${completedRecognition} ${finalText} ${interimText}`);$('liveCount').textContent=liveSupported?String(words):'—';$('liveSpeed').textContent=liveSupported&&elapsed>=3?`${Math.round(words*60/elapsed)} ppm`:'—';$('liveTranscript').textContent=`${completedRecognition} ${finalText} ${interimText}`.trim()||'Esperando voz…';}
function startRecognition(token){const Recognition=window.SpeechRecognition||window.webkitSpeechRecognition;liveSupported=!!Recognition;if(!Recognition){$('liveNotice').textContent='Este navegador no ofrece transcripción en directo. Puedes grabar y obtener el análisis final; para el directo, prueba Chrome o Edge.';return;}
  const instance=new Recognition();recognition=instance;instance.lang='es-ES';instance.continuous=true;instance.interimResults=true;
  instance.onresult=event=>{if(token!==session||!['recording','stopping'].includes(state))return;finalText='';interimText='';for(const result of event.results){if(result.isFinal)finalText+=result[0].transcript+' ';else interimText+=result[0].transcript+' ';}tick();};
  let blocked=false;
  instance.onerror=event=>{if(token!==session)return;$('liveNotice').textContent=`Transcripción en directo: ${event.error}. El audio sigue grabándose.`;if(['not-allowed','service-not-allowed','audio-capture','network'].includes(event.error)){blocked=true;liveSupported=false;$('liveSpeed').textContent='—';}};
  instance.onend=()=>{if(token!==session)return;completedRecognition+=finalText;finalText='';interimText='';if(state==='recording'&&!blocked){try{instance.start();}catch{liveSupported=false;$('liveNotice').textContent='El reconocimiento en directo se ha detenido; el audio continúa grabándose.';}}};
  try{instance.start();}catch(error){liveSupported=false;$('liveNotice').textContent='No se inició la transcripción en directo. Se conserva la grabación para el análisis final.';}
}
async function startRecording(){setState('starting');const token=++session;resetResults();$('analysisTag').textContent='Provisional';$('liveNotice').textContent='Velocidad estimada sobre el tiempo transcurrido, incluyendo pausas; puede actualizarse con retraso.';$('finalNotice').textContent='El audio se conserva temporalmente en esta pestaña.';completedRecognition=finalText=interimText='';$('liveTranscript').textContent='Esperando voz…';$('timer').textContent='00:00';$('liveCount').textContent='—';$('liveSpeed').textContent='—';setStatus('Solicitando micrófono…');
 try{if(!navigator.mediaDevices?.getUserMedia||!window.MediaRecorder)throw Error('Necesitas un navegador compatible y una conexión HTTPS.');stream=await navigator.mediaDevices.getUserMedia({audio:true});const types=['audio/webm;codecs=opus','audio/mp4','audio/webm'];const mime=types.find(t=>MediaRecorder.isTypeSupported(t));recorder=new MediaRecorder(stream,mime?{mimeType:mime}:undefined);const chunks=[];recorder.ondataavailable=event=>{if(event.data.size)chunks.push(event.data);};recorder.onerror=()=>{clearInterval(clock);recognition?.abort();releaseMic();setState('error');setStatus('La grabación falló. Inicia una nueva muestra.');};recorder.onstop=async()=>{clearInterval(clock);releaseMic();if(token!==session)return;attachAudio(new Blob(chunks,{type:recorder.mimeType}));await analyzeFinal();};recorder.start(1000);started=performance.now();setState('recording');setStatus('Grabando · datos provisionales');clock=setInterval(tick,250);startRecognition(token);
 }catch(error){releaseMic();setState('error');$('analysisTag').textContent='Error';setStatus(`No se pudo grabar: ${error.message}`);}}
function stopRecording(){if(state!=='recording')return;tick();clearInterval(clock);setState('stopping');setStatus('Finalizando grabación…');recognition?.stop();recorder.stop();}
async function decodeAudio(value){audioContext ||=new(window.AudioContext||window.webkitAudioContext)();const decoded=await audioContext.decodeAudioData(await value.arrayBuffer());const mono=new Float32Array(decoded.length);for(let c=0;c<decoded.numberOfChannels;c++){const channel=decoded.getChannelData(c);for(let i=0;i<mono.length;i++)mono[i]+=channel[i]/decoded.numberOfChannels;}const offline=new OfflineAudioContext(1,Math.ceil(decoded.duration*16000),16000);const buffer=offline.createBuffer(1,mono.length,decoded.sampleRate);buffer.copyToChannel(mono,0);const source=offline.createBufferSource();source.buffer=buffer;source.connect(offline.destination);source.start();const resampled=await offline.startRendering();return {samples:resampled.getChannelData(0),duration:decoded.duration};}
function transcribe(samples){return new Promise((resolve,reject)=>{const id=++job;try{worker ||=new Worker(new URL('./transcriber.worker.js',import.meta.url),{type:'module'});}catch(error){reject(error);return;}const fail=error=>{clearTimeout(workerTimeout);worker?.terminate();worker=null;reject(error);};worker.onerror=()=>fail(Error('No se pudo cargar el motor. Comprueba la conexión y que el navegador permita descargar el modelo.'));worker.onmessage=({data})=>{if(data.id!==id)return;if(data.type==='result'){clearTimeout(workerTimeout);resolve(data.output);}else if(data.type==='error')fail(Error(data.message));else if(data.type==='progress'){const p=data.progress;$('finalNotice').textContent=p.status==='transcribing'?'Transcribiendo el audio completo en este dispositivo… Puede tardar varios minutos.':`Preparando modelo local${Number.isFinite(p.progress)?` · ${Math.round(p.progress)} %`:''}. Primera descarga necesaria.`;}};workerTimeout=setTimeout(()=>fail(Error('El análisis excedió 15 minutos. El audio sigue disponible para descargar o reintentar.')),900000);const copy=samples.slice();worker.postMessage({id,audio:copy},[copy.buffer]);});}
async function analyzeFinal(){if(!blob)return;setState('processing');resetResults();$('analysisTag').textContent='Procesando audio completo';setStatus('Reprocesando · resultados finales pendientes');try{const {samples,duration}=await decodeAudio(blob);if(!duration||!samples.length)throw Error('El archivo no contiene audio.');const activity=acousticActivity(samples,16000);$('totalDuration').textContent=`${formatTime(duration)} · ${duration.toFixed(1)} s`;$('speechDuration').textContent=`${activity.speech.toFixed(1)} s`;$('silenceDuration').textContent=`${activity.silence.toFixed(1)} s`;$('pauseCount').textContent=String(activity.pauses.length);$('pauses').textContent=activity.pauses.length?activity.pauses.map(p=>`${formatTime(p.start)}–${formatTime(p.end)} (${p.duration.toFixed(2)} s)`).join(' · '):'No se detectaron pausas internas de 0,5 s o más.';
 let output;if(activity.speech===0){output={text:'',chunks:[]};}else output=await transcribe(samples);
 const words=countWords(output.text||'');const mean=words*60/duration;$('wordCount').textContent=String(words);$('wpm').textContent=`${Math.round(mean)} ppm`;$('finalTranscript').textContent=output.text?.trim()||'No se reconocieron palabras.';const temporal=wordSegments(output.chunks,duration);const assigned=temporal.bins.reduce((n,b)=>n+b.words,0);if(temporal.untimed||assigned!==words){$('chartNotice').textContent='Velocidad por tramos no disponible: faltan marcas temporales válidas para algunas palabras. No se reparte el recuento artificialmente.';currentBins=[];}else{currentBins=temporal.bins;for(const bin of currentBins){const row=document.createElement('tr');for(const text of [`${formatTime(bin.start)}–${formatTime(bin.end)}`,String(bin.words),bin.wpm.toFixed(1)]){const cell=document.createElement('td');cell.textContent=text;row.append(cell);}$('segmentRows').append(row);}}currentMean=mean;drawChart();$('analysisTag').textContent='Resultado final automático';$('finalNotice').textContent='Audio completo reprocesado con Whisper Base · marcas temporales automáticas · no validado clínicamente.';setState('done');setStatus('Análisis final completado');
 }catch(error){$('analysisTag').textContent='Análisis final incompleto';$('finalNotice').textContent=`No se completó la transcripción final: ${error.message}. El audio sigue disponible. Los datos en directo no se presentan como resultado final.`;setState('error');setStatus('Audio conservado · puedes reintentar el análisis');}}
function drawChart(){const canvas=$('speedChart'),ctx=canvas.getContext('2d');const w=canvas.clientWidth||600,h=260,dpr=window.devicePixelRatio||1;canvas.width=w*dpr;canvas.height=h*dpr;ctx.scale(dpr,dpr);ctx.clearRect(0,0,w,h);const color=getComputedStyle(document.body).getPropertyValue('--text');ctx.fillStyle=color;ctx.font='12px system-ui';if(!currentBins.length){ctx.fillText('Gráfico pendiente del análisis temporal final',20,40);return;}const left=45,right=w-15,top=25,bottom=h-40,max=Math.max(60,currentMean,...currentBins.map(b=>b.wpm))*1.2;const step=(right-left)/currentBins.length;for(let i=0;i<=4;i++){const y=bottom-(bottom-top)*i/4;ctx.strokeStyle='#94a3b855';ctx.beginPath();ctx.moveTo(left,y);ctx.lineTo(right,y);ctx.stroke();ctx.fillStyle=color;ctx.fillText(String(Math.round(max*i/4)),2,y+4);}currentBins.forEach((b,i)=>{const height=b.wpm/max*(bottom-top);ctx.fillStyle='#2d7ff9';ctx.fillRect(left+i*step+step*.15,bottom-height,step*.7,height);ctx.fillStyle=color;ctx.fillText(b.wpm.toFixed(0),left+i*step+step*.3,bottom-height-7);ctx.fillText(formatTime(b.start),left+i*step,bottom+20);});const y=bottom-currentMean/max*(bottom-top);ctx.strokeStyle='#c27616';ctx.setLineDash([5,4]);ctx.beginPath();ctx.moveTo(left,y);ctx.lineTo(right,y);ctx.stroke();ctx.setLineDash([]);ctx.fillStyle=color;ctx.fillText('ppm · línea discontinua = media global',left,14);}
$('recordBtn').addEventListener('click',startRecording);$('stopBtn').addEventListener('click',stopRecording);$('retryBtn').addEventListener('click',analyzeFinal);$('fileInput').addEventListener('change',async event=>{const file=event.target.files[0];if(!file)return;++session;attachAudio(file);$('liveTranscript').textContent='Archivo importado: no hay transcripción en directo.';$('liveSpeed').textContent=$('liveCount').textContent='—';await analyzeFinal();event.target.value='';});$('themeSwitch').addEventListener('click',()=>{document.body.dataset.theme=document.body.dataset.theme==='dark'?'light':'dark';drawChart();});window.addEventListener('resize',drawChart);window.addEventListener('beforeunload',()=>{clearInterval(clock);recognition?.abort();releaseMic();worker?.terminate();if(url)URL.revokeObjectURL(url);});setState('idle');drawChart();
