import test from 'node:test';
import assert from 'node:assert/strict';
import {LivePitchEngine} from '../live-pitch.mjs';
const limits={floor:75,ceiling:600};
function signal(rate,seconds,fn){return Float32Array.from({length:Math.round(rate*seconds)},(_,i)=>fn(i/rate));}
function feed(samples,rate,parts=[Math.round(rate*.06)],diagnostic=false){const e=new LivePitchEngine(rate,limits,{diagnostic}),points=[];for(let at=0,i=0;at<samples.length;i++){const end=Math.min(samples.length,at+parts[i%parts.length]);points.push(...e.push(samples.subarray(at,end),end));at=end;}return {e,points};}
for(const rate of [44100,48000])test('causal known tones and low-amplitude voice at '+rate,()=>{for(const hz of [80,180,400])for(const amplitude of [.1,.001]){const x=signal(rate,.5,t=>amplitude*Math.sin(2*Math.PI*hz*t)),{points}=feed(x,rate),valid=points.filter(p=>p.hz!==null);assert.ok(valid.length>=14);assert.ok(valid.every(p=>Math.abs(p.hz-hz)<1));assert.ok(points.every(p=>p.time<=x.length/rate-2048/(2*rate)));}});
test('zero signal and reproducible broadband noise do not become voiced',()=>{let seed=92;const noise=()=>{seed=(1664525*seed+1013904223)>>>0;return (seed/2**32-.5)*.012;};for(const x of [new Float32Array(48000),signal(48000,1,noise)])assert.ok(feed(x,48000).points.every(p=>p.hz===null));});
test('irregular block delivery and regular delivery use identical causal windows',()=>{const x=signal(48000,1,t=>.1*Math.sin(2*Math.PI*200*t)),a=feed(x,48000),b=feed(x,48000,[128,2048,17,3071,400]);assert.deepEqual(a.points,b.points);const half=feed(x.subarray(0,24000),48000);assert.deepEqual(half.points,a.points.filter(p=>p.time<=.5-2048/(2*48000)));});
test('silence windows remain null, octave-family harmonic is not shortened',()=>{const x=signal(48000,2,t=>t>.6&&t<1.3?0:.1*Math.sin(2*Math.PI*150*t)+.5*Math.sin(2*Math.PI*450*t)),{points}=feed(x,48000);assert.ok(points.filter(p=>p.time>.7&&p.time<1.2).every(p=>p.hz===null));assert.ok(points.filter(p=>p.hz!==null).every(p=>Math.abs(p.hz-150)<1));});
test('diagnostic is off by default; enabled statistics are local and bounded',()=>{const x=signal(48000,.5,t=>.1*Math.sin(2*Math.PI*180*t));const off=feed(x,48000).e.report();assert.deepEqual(off.recent,[]);assert.equal(off.series.rms,null);const e=feed(x,48000,undefined,true).e;e.noteRender(4);const on=e.report();assert.ok(on.windows>0);assert.ok(on.candidates>=on.accepted);assert.ok(on.series.rms.median>0);assert.equal(on.acceptedPointsVisible,4);assert.ok(on.recent.length<=100);});
test('capture count discontinuity resets window rather than joining missing audio',()=>{const e=new LivePitchEngine(48000,limits,{diagnostic:true});e.push(new Float32Array(2880),2880);e.push(new Float32Array(100),4000);assert.equal(e.report().captureGaps,1);assert.equal(e.fill,100);});
test('119-second incremental recording remains bounded',()=>{const x=signal(48000,119,t=>t%3>2?0:.1*Math.sin(2*Math.PI*180*t)),{e,points}=feed(x,48000,undefined,true);assert.ok(points.length<6000);assert.equal(e.report().recent.length,100);assert.ok(e.series.rms.length<=6500);assert.ok(points.filter(p=>p.time%3>2.2&&p.time%3<2.8).every(p=>p.hz===null));});
