import test from 'node:test';
import assert from 'node:assert/strict';
import {LiveAnalysisClient} from '../live-analysis-client.mjs';
import {LiveAnalysisProcessor} from '../live-analysis.worker.mjs';
import {LivePitchEngine} from '../live-pitch.mjs';
const rate=48000,limits={floor:75,ceiling:600};
function harness(){const messages=[],results=[],errors=[],worker={postMessage(m){messages.push(m);},terminate(){this.terminated=true;}},c=new LiveAnalysisClient({createWorker:()=>worker,onresult:r=>results.push(r),onerror:e=>errors.push(e),now:()=>100});return {c,worker,messages,results,errors};}
async function ready(h){const p=h.c.init(rate,limits);h.worker.onmessage({data:{type:'ready',report:{enabled:false}}});await p;h.messages.length=0;}
test('worker processor matches in-process F0, same spectral clock, and never mutates PCM',()=>{const x=Float32Array.from({length:4800},(_,i)=>.1*Math.sin(2*Math.PI*180*i/rate)),copy=x.slice(),p=new LiveAnalysisProcessor();p.init(rate,limits,{diagnostic:true});const result=p.audio({audio:x.buffer,endFrame:x.length,capturedAt:0,deliveryAgeMs:0}),expected=new LivePitchEngine(rate,limits).push(x,x.length);assert.deepEqual(result.points,expected);assert.deepEqual(result.columns.map(c=>c.time),result.points.map(c=>c.time));assert.deepEqual(x,copy);assert.equal(p.spectrum.columns.length,0);assert.equal(p.report().spectrum.columns,result.columns.length);});
test('single in-flight, transferable copy preserves recording, and flush follows final results',async()=>{const h=harness();await ready(h);const x=new Float32Array(960).fill(.1);h.c.push(x,960);h.c.push(x,1920);assert.equal(h.messages.length,1);assert.notEqual(h.messages[0].audio,x.buffer);const flush=h.c.flush();assert.equal(h.messages.length,1);h.worker.onmessage({data:{type:'result',points:[],columns:[],endFrame:960,capturedAt:100,deliveryAgeMs:0}});assert.equal(h.messages[1].endFrame,1920);h.worker.onmessage({data:{type:'result',points:[],columns:[],endFrame:1920,capturedAt:100,deliveryAgeMs:0}});assert.equal(h.messages[2].type,'flush');h.worker.onmessage({data:{type:'flushed',report:{windows:2}}});await flush;assert.equal(h.c.report().windows,2);h.c.close();assert.ok(h.worker.terminated);});
test('backpressure bounds pending audio, preserves latest sample clock, and reports skipped analysis',async()=>{const h=harness();await ready(h);for(let i=1;i<=30;i++)h.c.push(new Float32Array(960),i*960);assert.equal(h.c.pending.length,6);assert.equal(h.c.report().skippedAnalysisBlocks,23);h.worker.onmessage({data:{type:'result',points:[],columns:[],capturedAt:100,deliveryAgeMs:0}});assert.equal(h.messages[1].endFrame,25*960);h.c.close();});
test('worker errors reject drain, terminate DSP, and cannot update closed session',async()=>{const h=harness();await ready(h);h.c.push(new Float32Array(960),960);const drained=h.c.flush();h.worker.onmessage({data:{type:'error',message:'broken'}});await assert.rejects(drained,/broken/);assert.equal(h.errors.length,1);assert.ok(h.worker.terminated);h.c.close();h.worker.onmessage({data:{type:'result',points:[{hz:200}],columns:[]}});assert.equal(h.results.length,0);});
test('worker initialization failure is explicit',async()=>{const h=harness(),ready=h.c.init(rate,limits);h.worker.onerror({preventDefault(){}});await assert.rejects(ready,/no está disponible/);h.c.close();});
import {Worker as NodeWorker} from 'node:worker_threads';
test('real separate worker executes production module, drains final PCM and transfers spectra',async()=>{
 const results=[];let native;
 const client=new LiveAnalysisClient({onresult:r=>results.push(r),createWorker:()=>{
  native=new NodeWorker(`const {parentPort,workerData}=require('node:worker_threads');globalThis.self={postMessage:(data,transfer)=>parentPort.postMessage(data,transfer)};import(workerData).then(()=>parentPort.on('message',data=>self.onmessage({data})));`,{eval:true,workerData:new URL('../live-analysis.worker.mjs',import.meta.url).href});
  const adapter={postMessage:(data,transfer)=>native.postMessage(data,transfer),terminate:()=>native.terminate()};native.on('message',data=>adapter.onmessage?.({data}));native.on('error',error=>adapter.onerror?.(error));return adapter;
 }});
 try{await client.init(rate,limits,{diagnostic:true});const x=Float32Array.from({length:4800},(_,i)=>.1*Math.sin(2*Math.PI*200*i/rate)),copy=x.slice();for(let at=0;at<x.length;at+=960){const end=Math.min(x.length,at+960);client.push(x.subarray(at,end),end);}await client.flush();assert.deepEqual(x,copy);assert.equal(results.at(-1).endFrame,4800);const expected=new LivePitchEngine(rate,limits).push(x,x.length);assert.deepEqual(results.flatMap(r=>r.points),expected);assert.deepEqual(results.flatMap(r=>r.columns).map(c=>c.time),expected.map(c=>c.time));assert.ok(results.flatMap(r=>r.columns).some(c=>c.values.byteLength===128));assert.ok(client.report().spectrum.columns>0);}finally{client.close();}
});
