import test from 'node:test';
import assert from 'node:assert/strict';
import {performance} from 'node:perf_hooks';
import {contiguousRuns,curveSegments,VisualClock,movingWindow} from '../live-curve.mjs';
function value(s,t){const u=1-t;return Math.exp(u**3*Math.log(s.from.hz)+3*u*u*t*Math.log(s.c1.hz)+3*u*t*t*Math.log(s.c2.hz)+t**3*Math.log(s.to.hz));}
for(const [name,hzs] of Object.entries({stable:[200,200,200],rising:[100,150,240,400],falling:[400,240,150,100],rapid:[75,600,80,550,100],extremes:[50,1200,50]}))test(name+' interpolation stays inside each pair',()=>{const points=hzs.map((hz,i)=>({time:i*.06,hz})),copy=JSON.stringify(points);for(const s of curveSegments(points))for(let i=0;i<=100;i++){const hz=value(s,i/100);assert.ok(hz>=Math.min(s.from.hz,s.to.hz)-1e-9&&hz<=Math.max(s.from.hz,s.to.hz)+1e-9);}assert.equal(JSON.stringify(points),copy);});
test('null windows and irregular gaps split runs, never smoothed across',()=>{const points=[{time:0,hz:200},{time:.06,hz:220},{time:.12,hz:null},{time:.18,hz:300},{time:.25,hz:280},{time:.5,hz:250}];const runs=contiguousRuns(points);assert.deepEqual(runs.map(r=>r.map(p=>p.time)),[[0,.06],[.18,.25],[.5]]);assert.equal(runs.flatMap(curveSegments).length,2);});
test('visual clock adds a bounded horizon delay and freezes on stale arrivals',()=>{const clock=new VisualClock();clock.accept(1,1000);assert.equal(clock.at(1000).reveal,.9);assert.ok(Math.abs(clock.at(1050).reveal-.95)<1e-9);assert.equal(clock.at(3000).clock,1.12);assert.equal(clock.at(3000).reveal,1);clock.accept(1.2,3000);assert.ok(Math.abs(clock.at(3000).reveal-1.1)<1e-9);clock.reset();assert.equal(clock.at(3000).clock,0);});
test('rolling window keeps real seconds and moves continuously',()=>{const a=movingWindow(20),b=movingWindow(20.016);assert.equal(a.end-a.begin,3);assert.ok(Math.abs((b.begin-a.begin)-.016)<1e-9);assert.equal(movingWindow(0).begin,0);});
test('long rendering workload stays bounded to three-second geometry',()=>{const points=Array.from({length:2000},(_,i)=>({time:i*.06,hz:i%15===0?null:200+50*Math.sin(i*.1)}));const start=performance.now();let maximum=0;for(let i=0;i<1000;i++){const {begin,end}=movingWindow(119+i*.00001),visible=points.filter(p=>p.time>=begin-.12&&p.time<=end);maximum=Math.max(maximum,visible.length);contiguousRuns(visible).flatMap(curveSegments);}assert.ok(maximum<55);console.log('1000 geometry frames on 119 s data:',(performance.now()-start).toFixed(1),'ms; max visible:',maximum);});

test('late data arrivals never move the time window backwards',()=>{const c=new VisualClock();c.accept(1,0);const old=c.at(200).clock;c.accept(1.06,200);assert.ok(c.at(200).clock>=old);assert.ok(c.at(220).clock>=old);});
import {revealedTip} from '../live-curve.mjs';
test('revealed endpoint interpolates existing support only and disappears in null gaps',()=>{const p=[{time:0,hz:100},{time:.02,hz:120},{time:.04,hz:null},{time:.06,hz:200},{time:.08,hz:210}];const copy=JSON.stringify(p);for(const t of [.001,.01,.019]){const tip=revealedTip(p,t);assert.equal(tip.time,t);assert.ok(tip.hz>=100&&tip.hz<=120);}for(const t of [-.01,.03,.04,.05,.09])assert.equal(revealedTip(p,t),null);assert.equal(JSON.stringify(p),copy);});

test('one second occupies a third of live width without changing timestamps',()=>{const points=[{time:20,hz:120},{time:21,hz:180}],copy=JSON.stringify(points);const {begin,end}=movingWindow(21);const x=t=>(t-begin)/(end-begin);assert.ok(Math.abs(x(points[1].time)-x(points[0].time)-1/3)<1e-9);assert.equal(JSON.stringify(points),copy);assert.equal(movingWindow(21,8).end-movingWindow(21,8).begin,8);});
