import test from 'node:test';
import assert from 'node:assert/strict';
import vm from 'node:vm';
import {readFileSync} from 'node:fs';
function harness(){const nodes=new Map();const get=id=>{if(!nodes.has(id))nodes.set(id,{hidden:false,value:'',textContent:'',events:{},dataset:{},children:[],addEventListener(n,f){this.events[n]=f;},replaceChildren(...a){this.children=a;},append(n){this.children.push(n);}});return nodes.get(id);};const buttons=['speed','pitch','intensity','voice','guided'].map(k=>{const b=get('button-'+k);b.dataset.module=k;return b;});const body={dataset:{session:'done'}};let resized=0;const document={getElementById:get,querySelectorAll:()=>buttons,body,createElement:()=>({textContent:'',children:[],append(n){this.children.push(n);}})};const source=readFileSync(new URL('../navigation-prototype.mjs',import.meta.url),'utf8').replace("import './script.js';",'');vm.runInNewContext(source,{document,window:{scrollTo(){},dispatchEvent(){resized++;}},Event:class{}});return {get,body,choose:k=>get('button-'+k).events.click(),resized:()=>resized};}
test('speed navigation preserves existing results and guards return while recording',()=>{const h=harness();h.choose('speed');assert.equal(h.get('speedSurface').hidden,false);assert.equal(h.resized(),1);h.body.dataset.session='recording';h.get('speedHome').events.click();assert.equal(h.get('speedSurface').hidden,false);h.body.dataset.session='done';h.get('speedHome').events.click();assert.equal(h.get('speedSurface').hidden,true);assert.equal(h.get('modeHome').hidden,false);});
test('prototype source switches flow and renders empty values without processing audio',()=>{const h=harness();h.choose('intensity');assert.equal(h.get('previewTitle').textContent,'Control de intensidad');h.get('previewSource').value='upload';h.get('previewSource').events.change();assert.equal(h.get('previewAnalysisField').hidden,false);h.get('previewAnalysis').value='voice';h.get('showPracticePreview').events.click();assert.equal(h.get('resultsPreview').hidden,false);assert.equal(h.get('previewMetrics').children[0].children[0].textContent,'—');assert.match(h.get('previewLimit').textContent,/no se calculan/);});
test('guided module explicitly proposes several tasks and no synthetic measurement',()=>{const h=harness();h.choose('guided');assert.equal(h.get('guidedTasks').hidden,false);h.get('showPracticePreview').events.click();assert.equal(h.get('practicePreview').hidden,false);assert.match(h.get('practiceNote').textContent,/cada tarea/);const html=readFileSync(new URL('../index.html',import.meta.url),'utf8');const ids=[...html.matchAll(/\bid="([^"]+)"/g)].map(m=>m[1]);assert.equal(ids.length,new Set(ids).size);assert.match(html,/todavía no graban ni analizan audio/);});
test('pitch entry opens functional surface while preserving the speed module',()=>{const h=harness();h.choose('pitch');assert.equal(h.get('pitchSurface').hidden,false);assert.equal(h.get('speedSurface').hidden,true);assert.equal(h.get('modulePreview').hidden,true);assert.equal(h.get('modeHome').hidden,true);});
