import test from 'node:test';
import assert from 'node:assert/strict';
import vm from 'node:vm';
import {readFileSync} from 'node:fs';
import {PitchDetector} from '../vendor/pitchy-4.1.0.mjs';
import * as data from '../pitch-data.mjs';
import * as prosody from '../prosody.mjs';
function harness({denied=false,serverError=false}={}){
 const nodes=new Map(),brush={clearRect(){},beginPath(){},moveTo(){},lineTo(){},stroke(){},fillText(){},setTransform(){},save(){},rect(){},clip(){},arc(){},fill(){},restore(){},setLineDash(){}};
 const get=id=>{if(!nodes.has(id))nodes.set(id,{value:id==='pitchFloor'?'75':id==='pitchCeiling'?'600':id==='pitchTask'?'Habla espontánea':id==='pitchMode'?'free':id==='pitchGuideLow'?'130':id==='pitchGuideHigh'?'250':id==='pitchGuideDuration'?'4':'',checked:true,hidden:false,disabled:false,textContent:'',style:{},dataset:{},width:1000,height:360,currentTime:0,events:{},children:[],addEventListener(k,f){this.events[k]=f;},replaceChildren(...v){this.children=v;},append(...v){this.children.push(...v);},pause(){},play(){return Promise.resolve();},removeAttribute(k){delete this[k];},getContext(){return brush;},getBoundingClientRect(){return {left:0,width:800,height:360};}});return nodes.get(id);};
 let stopped=0,closed=0,requests=0,endFrame=0,capture,lastBlob,clock=0,lastBody,ctx;
 const stream={getTracks:()=>[{stop(){stopped++;}}]};
 class AudioContext{sampleRate=48000;get currentTime(){return clock;}audioWorklet={addModule:async()=>{}};constructor(){ctx=this;}resume(){return Promise.resolve();}close(){closed++;return Promise.resolve();}createGain(){return {gain:{value:1},connect(){},disconnect(){}};}createMediaStreamSource(){return {connect(){}};}decodeAudioData(){return Promise.resolve({duration:.18});}}
 class OfflineAudioContext{createBufferSource(){return {connect(){},start(){}};}startRendering(){return Promise.resolve({getChannelData:()=>new Float32Array(2880)});}}
 class AudioWorkletNode{constructor(){capture=this;}connect(){}disconnect(){}port={postMessage:()=>{this.port.onmessage({data:{audio:new Float32Array().buffer,endFrame,audioTime:clock,done:true}});}};}
 const document={documentElement:{},getElementById:get,body:{dataset:{session:'done'}},createElement:()=>({textContent:'',children:[],append(...n){this.children.push(...n);}})};
 const window={AudioContext,AudioWorkletNode,devicePixelRatio:1,requestAnimationFrame:f=>f(),addEventListener(){}};
 const source=readFileSync(new URL('../pitch-controller.mjs',import.meta.url),'utf8').replace(/^import .*;\n/gm,'');
 vm.runInNewContext(source,{document,window,navigator:{mediaDevices:{getUserMedia:async()=>{if(denied)throw Error('Permission denied');return stream;}}},OfflineAudioContext,AudioWorkletNode,Float32Array,Blob,AbortController,URL:{createObjectURL:b=>{lastBlob=b;return 'blob:test';},revokeObjectURL(){}},getComputedStyle:()=>({getPropertyValue:()=>''}),setTimeout:()=>1,clearTimeout(){},fetch:async(_url,options)=>{requests++;lastBody=options.body;return {ok:!serverError,status:503,json:async()=>({source:'Praat/Parselmouth',version:'0.4.7',praatVersion:'6.1.38',method:'raw autocorrelation',duration:.18,points:[{time:.1,hz:200},{time:.11,hz:null}]})};},PitchDetector,...data,...prosody});
 return {get,document,click:async(id,event)=>get(id).events.click(event),tick(){const size=2880,samples=Float32Array.from({length:size},(_,i)=>.3*Math.sin(2*Math.PI*200*(endFrame+i)/48000));endFrame+=size;clock=endFrame/48000;capture.port.onmessage({data:{audio:samples.buffer,endFrame,audioTime:clock,done:false}});},stopped:()=>stopped,closed:()=>closed,requests:()=>requests,blob:()=>lastBlob,body:()=>lastBody};
}
test('PCM capture drives tone and final analysis, flushes and releases microphone',async()=>{const h=harness();await h.click('pitchRecord');assert.equal(h.document.body.dataset.session,'recording');assert.equal(h.get('pitchSurface').dataset.view,'recording');assert.equal(h.get('pitchStop').disabled,false);h.tick();h.tick();h.tick();assert.match(h.get('pitchValue').textContent,/200 Hz/);assert.equal(h.requests(),0);await h.click('pitchStop');assert.equal(h.requests(),1);assert.equal(h.stopped(),1);assert.ok(h.closed()>=2);assert.equal(h.blob().type,'audio/wav');const wav=new DataView(await h.blob().arrayBuffer());assert.equal(wav.getUint32(24,true),48000);assert.equal(wav.getUint32(40,true)/2/48000,.18);assert.equal(new DataView(h.body()).getUint32(24,true),16000);assert.equal(h.get('pitchAudio').src,'blob:test');assert.match(h.get('pitchChartSource').textContent,/Análisis final.*Praat 6.1.38/);assert.equal(h.document.body.dataset.session,'done');assert.equal(h.get('pitchSurface').dataset.view,'results');assert.equal(h.get('pitchRecord').disabled,false);});
test('server failure preserves provisional curve, WAV and retry',async()=>{const h=harness({serverError:true});await h.click('pitchRecord');h.tick();h.tick();h.tick();await h.click('pitchStop');assert.match(h.get('pitchStatus').textContent,/no está disponible/);assert.match(h.get('pitchChartSource').textContent,/provisional/);assert.equal(h.get('pitchAudio').src,'blob:test');assert.equal(h.get('pitchRetry').disabled,false);assert.equal(h.get('pitchResults').hidden,false);assert.equal(h.get('pitchProcessing').hidden,true);});
test('denied microphone returns to setup without sending audio',async()=>{const h=harness({denied:true});await h.click('pitchRecord');assert.equal(h.document.body.dataset.session,'done');assert.match(h.get('pitchStatus').textContent,/Permission denied/);assert.equal(h.requests(),0);assert.equal(h.get('pitchRecord').disabled,false);});
test('invalid bounds stop before microphone and navigation cannot leave busy capture',async()=>{const h=harness();h.get('pitchFloor').value='200';h.get('pitchCeiling').value='250';await h.click('pitchRecord');assert.match(h.get('pitchStatus').textContent,/Revisa los límites/);assert.equal(h.requests(),0);h.get('pitchFloor').value='75';h.get('pitchCeiling').value='600';await h.click('pitchRecord');await h.click('pitchHome');assert.equal(h.get('modeHome').hidden,false);assert.equal(h.get('pitchHome').disabled,true);});
test('chart seeking uses the actual sample duration and keyboard navigation',async()=>{const h=harness();await h.click('pitchRecord');h.tick();h.tick();h.tick();await h.click('pitchStop');await h.click('pitchChart',{clientX:420});assert.ok(Math.abs(h.get('pitchAudio').currentTime-.09)<.001);h.get('pitchChart').events.keydown({key:'Home',preventDefault(){}});assert.equal(h.get('pitchAudio').currentTime,0);h.get('pitchChart').events.keydown({key:'End',preventDefault(){}});assert.equal(h.get('pitchAudio').currentTime,.18);});

test('two attempts preserve their audio and use original common timeline',async()=>{const h=harness();await h.click('pitchRecord');h.tick();h.tick();h.tick();await h.click('pitchStop');await h.click('pitchAgain');assert.equal(h.get('pitchRecord').disabled,false);assert.match(h.get('pitchStatus').textContent,/Preparado/);await h.click('pitchRecord');h.tick();h.tick();h.tick();await h.click('pitchStop');assert.match(h.get('pitchComparison').textContent,/Intento 1.*Intento 2/);await h.click('pitchAttempt0');assert.match(h.get('pitchContext').textContent,/Habla espontánea/);assert.equal(h.get('pitchAudio').src,'blob:test');});

test('free practice needs no text, chart exists first and real PCM populates it',async()=>{const h=harness();assert.equal(h.get('pitchSurface').dataset.view,'setup');assert.equal(h.get('pitchPrompt').hidden,true);assert.equal(h.get('pitchChart').width,800);await h.click('pitchRecord');h.tick();h.tick();h.tick();assert.match(h.get('pitchValue').textContent,/200 Hz/);await h.click('pitchStop');assert.match(h.get('pitchChartSource').textContent,/Praat/);});
test('two attempts block accidental third recording until explicit replacement',async()=>{const h=harness();for(let i=0;i<2;i++){await h.click('pitchRecord');h.tick();h.tick();h.tick();await h.click('pitchStop');await h.click('pitchAgain');}assert.equal(h.get('pitchRecord').disabled,true);assert.equal(h.get('pitchCapacity').hidden,false);const before=h.get('pitchComparison').textContent;await h.click('pitchRecord');assert.match(h.get('pitchStatus').textContent,/dos intentos/);assert.equal(h.requests(),2);assert.equal(h.get('pitchComparison').textContent,before);await h.click('pitchReplace0');assert.equal(h.get('pitchRecord').disabled,false);await h.click('pitchRecord');h.tick();h.tick();h.tick();await h.click('pitchStop');assert.equal(h.requests(),3);assert.match(h.get('pitchComparison').textContent,/Intento 1.*Intento 2/);});
test('phrases and reading keep optional text when hidden',async()=>{const h=harness();for(const task of ['Frases','Lectura']){h.get('pitchTask').value=task;h.get('pitchText').value='¿Vienes conmigo?';h.get('pitchTextVisible').checked=true;h.get('pitchText').events.change();assert.equal(h.get('pitchPrompt').textContent,'¿Vienes conmigo?');assert.equal(h.get('pitchPrompt').hidden,false);h.get('pitchTextVisible').checked=false;h.get('pitchTextVisible').events.change();assert.equal(h.get('pitchPrompt').hidden,true);assert.equal(h.get('pitchText').value,'¿Vienes conmigo?');await h.click('pitchRecord');h.tick();h.tick();h.tick();await h.click('pitchStop');assert.match(h.get('pitchContext').textContent,new RegExp(task));await h.click('pitchAgain');}});
test('workspace precedes collapsed options and no manual attempt selector remains',()=>{const html=readFileSync(new URL('../index.html',import.meta.url),'utf8');assert.ok(html.indexOf('id="pitchWorkspace"')<html.indexOf('id="pitchConfiguration"'));assert.match(html,/<details id="pitchConfiguration"[^>]*><summary>/);assert.doesNotMatch(html,/id="pitchSlot"/);const css=readFileSync(new URL('../style.css',import.meta.url),'utf8');assert.doesNotMatch(css,/data-view=setup\] #pitchWorkspace\{display:none/);});
