import test from 'node:test';
import assert from 'node:assert/strict';
import {LivePitchEngine,LIVE_CONFIG} from '../live-pitch.mjs';
import {LiveToneTracker} from '../pitch-data.mjs';
import {AdaptiveEnergyGate} from '../adaptive-energy.mjs';
import {LIVE_WINDOW_OPTIONS,liveWindowSeconds,movingWindow,timeTicks} from '../live-curve.mjs';
import {SpectralEngine} from '../spectrogram.mjs';
const limits={floor:75,ceiling:600};
const synth=(rate,seconds,f)=>Float32Array.from({length:Math.round(rate*seconds)},(_,i)=>f(i/rate));
function run(x,rate,config=LIVE_CONFIG){const e=new LivePitchEngine(rate,limits,{config,diagnostic:true}),p=[];for(let at=0;at<x.length;at+=137){const end=Math.min(x.length,at+137);p.push(...e.push(x.subarray(at,end),end));}return {e,p};}
for(const rate of [44100,48000])test('actual estimates every 5 ms with 2048-sample overlap and matching STFT at '+rate,()=>{const x=synth(rate,1,t=>.05*Math.sin(2*Math.PI*180*t)),copy=x.slice(),{e,p}=run(x,rate),s=new SpectralEngine(rate);s.push(x,x.length);assert.equal(e.config.size,2048);assert.equal(e.hop,Math.round(rate*.005));assert.equal(p.length,Math.floor(rate/e.hop)-Math.ceil(2048/e.hop)+1);for(let i=1;i<p.length;i++)assert.ok(Math.abs(p[i].time-p[i-1].time-e.hop/rate)<1e-9);assert.deepEqual(s.columns.map(c=>c.time),p.map(q=>q.time));assert.deepEqual(x,copy);});
for(const window of [.5,2,3,5,8,10])test('real-time view '+window+' seconds has distinct readable ticks, continuous motion and no state mutation',()=>{const a=movingWindow(118,window),b=movingWindow(118.016,window);assert.ok(Math.abs(a.end-a.begin-window)<1e-9);assert.ok(Math.abs(b.begin-a.begin-.016)<1e-9);for(const width of [180,600]){const ticks=timeTicks(a.begin,a.end,width);assert.equal(new Set(ticks.map(t=>t.label)).size,ticks.length);for(let i=1;i<ticks.length;i++){const previous=ticks[i-1],current=ticks[i];const extent=t=>{const n=t.label.length*7,x=t.fraction*width;return t.align==='left'?[x,x+n]:t.align==='right'?[x-n,x]:[x-n/2,x+n/2];};assert.ok(extent(current)[0]>=extent(previous)[1]);}}});
test('selector admits exactly six values; half-second view does not reserve half its width for future audio',()=>{assert.deepEqual(LIVE_WINDOW_OPTIONS,[.5,2,3,5,8,10]);assert.equal(liveWindowSeconds('0.5'),.5);for(const bad of [0,1,6,11,NaN,'oops'])assert.equal(liveWindowSeconds(bad),5);assert.ok(movingWindow(20,.5).end-20<.05);});
for(const rate of [44100,48000])test('weak periodic input below old RMS limit gains valid estimates without PCM normalization at '+rate,()=>{const x=synth(rate,1,t=>.00015*Math.sin(2*Math.PI*180*t)),copy=x.slice(),old=run(x,rate,{...LIVE_CONFIG,adaptiveEnergy:false,recoverySeconds:0}),next=run(x,rate);assert.ok(old.p.every(p=>p.hz===null));assert.ok(next.p.filter(p=>p.hz!==null).length>=30);assert.ok(next.p.filter(p=>p.hz!==null).every(p=>Math.abs(p.hz-180)<1));assert.deepEqual(x,copy);});
test('background floor resists one knock and prevents weak input passing solely on volume',()=>{const g=new AdaptiveEnergyGate(LIVE_CONFIG);for(let i=0;i<20;i++)g.threshold(.0001,.2,0);g.threshold(.1,.1,0);assert.ok(g.report().noiseFloorRms<.00011);assert.ok(Math.abs(g.threshold(.00015,.95,0)-.0003)<1e-12);assert.equal(g.threshold(.00015,.81,0),.0005);for(let i=0;i<100;i++)g.threshold(.0001,.1,0);assert.equal(g.noise.length,60);});
test('close high-periodicity tone reacquires first true candidate after 90 ms gap; missing windows remain null',()=>{const old=new LiveToneTracker({...LIVE_CONFIG,recoverySeconds:0}),next=new LiveToneTracker(LIVE_CONFIG);for(const t of [0,.03]){old.update(180,.96,.01,0,t,75,600);next.update(180,.96,.01,0,t,75,600);}for(const t of [.06,.09]){assert.equal(old.update(0,0,.01,0,t,75,600).hz,null);assert.equal(next.update(0,0,.01,0,t,75,600).hz,null);}assert.equal(old.update(182,.96,.01,0,.12,75,600).hz,null);const p=next.update(182,.96,.01,0,.12,75,600);assert.equal(p.hz,182);assert.equal(p.reason,'recovered');assert.equal(p.recoveryMs,60);});
test('recovery does not bypass octave confirmation, long silence or digital clipping',()=>{for(const kind of ['octave','long','clipped']){const t=new LiveToneTracker(LIVE_CONFIG);t.update(180,.96,.01,0,0,75,600);t.update(180,.96,.01,0,.03,75,600);t.update(0,0,.01,kind==='clipped'?.02:0,.06,75,600);t.update(0,0,.01,0,.09,75,600);const p=t.update(kind==='octave'?360:180,.96,.01,0,kind==='long'?.3:.12,75,600);assert.equal(p.hz,null);assert.equal(p.reason,'confirmation');}});
test('noise, silent intervals and below-range fan-like tone stay null with adaptive energy',()=>{let seed=77;const noise=()=>{seed=(1664525*seed+1013904223)>>>0;return (seed/2**32-.5)*.001;};for(const x of [new Float32Array(48000),synth(48000,1,noise),synth(48000,1,t=>.00015*Math.sin(2*Math.PI*50*t)+noise()*.01)])assert.ok(run(x,48000).p.every(p=>p.hz===null));});

import {compareMeasuredFrames} from '../pitch-comparison.mjs';
test('frequency comparison uses true frame times and separates transition disagreements from stable null regions',()=>{const reference=Array.from({length:41},(_,i)=>({time:i*.01,hz:i>=15&&i<=18?180:null})),points=[{time:.15,hz:180},{time:.20,hz:180},{time:.30,hz:180}];const r=compareMeasuredFrames(points,reference);assert.equal(r.bothVoiced,1);assert.equal(r.directWhenPraatNull,2);assert.equal(r.stableUnvoicedAccepted,1);assert.equal(r.p90Cents,0);assert.equal(compareMeasuredFrames([],[]).p90Cents,null);});
