import test from 'node:test';
import assert from 'node:assert/strict';
import {serializeSession,parseSession,SESSION_PROVENANCE} from '../session.mjs';
function fixture(){return {blob:new Blob([new Uint8Array([1,2,3,4])],{type:'audio/webm;codecs=opus'}),task:'reading',target:{min:120,max:150},createdAt:'2026-10-07T12:00:00Z',provenance:{...SESSION_PROVENANCE},result:{duration:20,activity:{speech:15,silence:5,threshold:.006,pauses:[{start:3,end:4,duration:1}]},output:{text:'hola mundo',chunks:[{text:'hola',timestamp:[1,2]},{text:'mundo',timestamp:[16,17]}]}},provisional:{duration:20,mean:6,bins:[{start:0,end:3,wpm:null},{start:3,end:20,wpm:135}]}};}
const mutate=async(fn)=>{const obj=JSON.parse(await (await serializeSession(fixture())).text());fn(obj);return new Blob([JSON.stringify(obj)]);};
test('session round trip preserves bytes, source, target, timing and provisional snapshot',async()=>{const original=fixture(),restored=await parseSession(await serializeSession(original),10);assert.deepEqual(new Uint8Array(await restored.blob.arrayBuffer()),new Uint8Array([1,2,3,4]));assert.equal(restored.blob.type,original.blob.type);assert.equal(restored.task,'reading');assert.deepEqual(restored.target,original.target);assert.deepEqual(restored.provisional,original.provisional);assert.equal(restored.createdAt,original.createdAt);assert.equal(restored.result.mean,6);assert.equal(restored.result.bins.length,2);assert.deepEqual(restored.provenance,original.provenance);});
test('provisional-only session is recoverable without inventing final analysis',async()=>{const f=fixture();f.result=null;const restored=await parseSession(await serializeSession(f));assert.equal(restored.result,null);assert.equal(restored.provisional.bins[0].wpm,null);});
test('version, invalid targets, malformed base64 and inconsistent acoustics are rejected',async()=>{for(const fn of [o=>o.version=99,o=>o.provenance.analysisVersion='future',o=>o.target.min=200,o=>o.audio.base64='http://evil',o=>o.result.activity.speech=100,o=>o.provisional.bins[1].start=1])await assert.rejects(parseSession(await mutate(fn)));await assert.rejects(parseSession(new Blob(['{broken'])));});
test('missing timestamps retain mean and do not invent final graph',async()=>{const f=fixture();f.result.output.chunks=[];const restored=await parseSession(await serializeSession(f));assert.equal(restored.result.words,2);assert.equal(restored.result.bins,null);});
test('empty/oversize files and empty audio are rejected before decoding',async()=>{await assert.rejects(parseSession({size:80*1024*1024,text(){throw Error('must not read');}}));const f=fixture();f.blob=new Blob([]);await assert.rejects(serializeSession(f));});
