import test from 'node:test';
import assert from 'node:assert/strict';
import {YinPitchDetector} from '../yin-pitch.mjs';
import {LivePitchEngine} from '../live-pitch.mjs';
import {LiveAnalysisProcessor} from '../live-analysis.worker.mjs';
for(const rate of [44100,48000])for(const hz of [55,80,150,350,950])test('YIN estimates harmonic F0 '+hz+' at '+rate,()=>{const x=Float32Array.from({length:rate/2},(_,i)=>.04*Math.sin(2*Math.PI*hz*i/rate)+.07*Math.sin(4*Math.PI*hz*i/rate)+.03*Math.sin(6*Math.PI*hz*i/rate)),copy=x.slice(),e=new LivePitchEngine(rate,{floor:50,ceiling:1000},{engine:'yin'}),p=e.push(x,x.length).filter(p=>p.time>.1),v=p.filter(p=>p.hz!==null);assert.ok(v.length/p.length>.9);assert.ok(v.every(p=>Math.abs(1200*Math.log2(p.hz/hz))<30));assert.deepEqual(x,copy);});
test('YIN silence/noise are not invented pitches, and limits apply',()=>{let seed=83;for(const x of [new Float32Array(2048),Float32Array.from({length:2048},()=>{seed=(1664525*seed+1013904223)>>>0;return (seed/2**32-.5)*.3;})])assert.deepEqual(new YinPitchDetector(2048).findPitch(x,48000,50,1000),[0,0]);const x=Float32Array.from({length:2048},(_,i)=>.1*Math.sin(2*Math.PI*40*i/48000));assert.deepEqual(new YinPitchDetector(2048).findPitch(x,48000,75,600),[0,0]);});
test('worker receives YIN choice and keeps exact shared F0/STFT timestamps',()=>{const x=Float32Array.from({length:9600},(_,i)=>.1*Math.sin(2*Math.PI*150*i/48000)),copy=x.slice(),p=new LiveAnalysisProcessor();assert.equal(p.init(48000,{floor:50,ceiling:1000},{engine:'yin',diagnostic:true}).engine,'yin');const r=p.audio({audio:x.buffer,endFrame:x.length,deliveryAgeMs:0,capturedAt:0});assert.deepEqual(r.points.map(p=>p.time),r.columns.map(c=>c.time));assert.deepEqual(x,copy);assert.equal(p.report().engine,'yin');assert.ok(r.points.some(p=>p.hz!==null));});
test('unknown motor is an explicit error, current remains default',()=>{assert.throws(()=>new LivePitchEngine(48000,{floor:50,ceiling:1000},{engine:'wrong'}),/desconocido/);assert.equal(new LivePitchEngine(48000,{floor:50,ceiling:1000}).report().engine,'current');});
